# AWS CLI
# https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html

- name: AWSCLI - Install for Darwin
  when: ansible_os_family in ["Darwin"]
  homebrew:
    name: awscli
    state: present


- name: AWSCLI - Install for Debian
  when: ansible_os_family in ["Debian"]
  become: "{{ should_be_root }}"
  block:
    - name: Get archive and unzip it
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: yes
    
    - name: Install awscli
      shell: |
        sudo /tmp/aws/install -i /usr/local/aws-cli -b /usr/local/bin
    
    - name: Verify AWS installation
      command: which aws
      register: which_aws
    
    - name: AWSCLI - which aws?
      debug: msg="which aws?{{ which_aws.stdout }}"
