---
# debian task for gparted

- name: gparted is present for debian system
  block:
    - name: Ensure dependencies are installed
      apt:
        name:
          - gparted
          - gpart
        state: present
