---
# debian task for sublime-text

- name: sublime-text is present for debian system
  block:
    - name: Install Sublime Text GPG key
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present

    - name: Install dependencies for Sublime Text
      apt:
        name:
          - apt-transport-https
        state: present

    - name: Install Sublime Text repository
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        filename: sublime-text
        state: present

    - name: Install Sublime Text
      apt:
        name: sublime-text
        state: present
        update_cache: true
