---
# main task for wallpaper

- name: Symlink wallpaper for debian
  file:
    src: "{{ ansible_dir }}/roles/infrastructure/wallpaper/files/forest-sunset.jpg"
    dest: "{{ dotfiles_user_home }}/Pictures/forest-sunset.jpg"
    state: link
  when: ansible_os_family in ["Debian",  "Pop!_OS" ]
