---
# main task for virtualbox

- name: virtualbox is present
  become: "{{ should_be_root }}"

  block:
    - name: virtualbox is present (linux)
      when: ansible_pkg_mgr != 'homebrew'
      package:
        name: virtualbox
        state: latest

    - name: virtualbox is present (homebrew cask)
      when: ansible_pkg_mgr == 'homebrew'
      homebrew_cask:
        name: virtualbox
        state: present
