---
# Multiple GNOME terminals in one window!
# https://gnome-terminator.org/

- name: TERMINATOR - Install, get plugins and symlink config (Linux)
  block:
    - name: TERMINATOR - Install
      package:
        name: terminator
        state: present

    - name: TERMINATOR - Create terminator plugin directory
      file:
        path: "{{ dotfiles_user_home }}/.config/terminator/plugins"
        state: directory
        mode: "775"
    
    - name: TERMINATOR - Get terminator-themes plugin
      get_url:
        url: "https://git.io/v5Zww"
        dest: "{{ dotfiles_user_home }}/.config/terminator/plugins/terminator-themes.py"
    
    - name: TERMINATOR - Symlink terminator config file
      file:
        src: "{{ playbook_dir }}/files/linux/terminator-config"
        dest: "{{ dotfiles_user_home }}/.config/terminator/config"
        state: link
        force: yes
  become: "{{ should_be_root }}"
  when: ansible_os_family in ["Debian"]
