# github - software installed directly from software

# CLI

delta_project: dandavison/delta
delta_version: 0.8.3

exa_project: ogham/exa
exa_version: 0.10.1

jump_project: gsamokovarov/jump
jump_version: 0.40.0

noti_project: variadico/noti
noti_version: 3.5.0

# Infrastructure

dockercompose_project: docker/compose
dockercompose_version: 1.29.2

# Software

rambox_project: ramboxapp/community-edition
rambox_version: 0.7.9

simplenote_project: Automattic/simplenote-electron
simplenote_version: 2.16.0
