# vs code extensions

visual_studio_code_extensions:
  - alexcvzz.vscode-sqlite
  - ban.spellright
  - CoenraadS.bracket-pair-colorizer-2
  - DavidAnson.vscode-markdownlint
  - donjayamanne.githistory
  - dotiful.dotfiles-syntax-highlighting
  - eamodio.gitlens
  - equinusocio.vsc-material-theme-icons
  - formulahendry.code-runner
  - golang.go
  - kiteco.kite
  - mads-hartmann.bash-ide-vscode
  - mgmcdermott.vscode-language-babel
  - ms-azuretools.vscode-docker
  - ms-python.python
  - ms-python.vscode-pylance
  - njpwerner.autodocstring
  - redhat.vscode-yaml
  - rust-lang.rust
  - samuelcolvin.jinjahtml
  - Shan.code-settings-sync
  - vscodevim.vim
  - wesbos.theme-cobalt2
  - yzane.markdown-pdf
  - yzhang.markdown-all-in-one
