- name: Update apt cache
  apt:
    update_cache: yes
  when: package_update
  become: yes
  become_user: root
  become_method: sudo

- name: Upgrade apt packages
  apt:
    upgrade: "yes"
  when: package_upgrade
  become: yes
  become_user: root
  become_method: sudo

- name: Install apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ apt_packages }}"
