---
# main task for plex

- name: plex is present
  become: "{{ should_be_root }}"

  block:
    - name: plex is present (debian)
      import_tasks: debian.yml
      when: ansible_os_family in ["Debian",  "Pop!_OS"]

    - name: plex is present (darwin)
      import_tasks: darwin.yml
      when: ansible_os_family in ["Darwin"]
