---
# main task for plex

- name: plex is present (darwin)
  debug:
    msg: "TODO: Implement for Darwin"
  when: ansible_os_family == "Darwin"


- name: PLEX - present for (debian)
  become: "{{ should_be_root }}"

  block:
    - name: PLEX - Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: PLEX - Add Plex apt key (Ubuntu & Debian with systemd)
      apt_key:
        url: https://downloads.plex.tv/plex-keys/PlexSign.key
        state: present

    - name: PLEX - Add Plex apt repo (Ubuntu & Debian with systemd)
      apt_repository:
        repo: deb https://downloads.plex.tv/repo/deb public main
        state: present
      changed_when: false

    - name: PLEX - Apt install Plex
      apt:
        name: plexmediaserver
        state: present
        update_cache: true
      notify: restart plex

    - name: PLEX - Autostart Plex
      service:
        name: plexmediaserver
        enabled: true
      notify: restart plex
  when: ansible_os_family in ["Debian"]

