---
# main task for plex

- name: plex is present (darwin)
  debug:
    msg: "TODO: Implement for Darwin"
  when: ansible_os_family == "Darwin"


- name: PLEX - present for (debian)
  become: "{{ should_be_root }}"

  block:
    - name: PLEX - Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: PLEX - Add Plex apt repo (Ubuntu & Debian with systemd)
      ansible.builtin.deb822_repository:
        name: plexmediaserver
        types: deb
        uris: https://downloads.plex.tv/repo/deb
        suites: public
        components: main
        signed_by: https://downloads.plex.tv/plex-keys/PlexSign.key
        state: present

    - name: PLEX - Apt install Plex
      apt:
        name: plexmediaserver
        state: present
        update_cache: true
      notify: restart plex

    - name: PLEX - Autostart Plex
      service:
        name: plexmediaserver
        enabled: true
      notify: restart plex
  when: ansible_os_family in ["Debian"]

