- name: Set up local workstation
  hosts: local
  vars:
    should_be_root: "{{ true if ansible_pkg_mgr != 'brew' else false }}"
  roles:
    # infrastructure
    - { role: infrastructure/docker, tags: [docker] }
    - { role: infrastructure/fonts-firacode, tags: [fonts-firacode] }
    - { role: infrastructure/git, tags: [git] }
    - { role: infrastructure/gparted, tags: [gparted] }
    - { role: infrastructure/linux-snap, tags: [linux-snap] }
    - { role: infrastructure/linux-terminator, tags: [linux-terminator] }
    - { role: infrastructure/linux-openssh, tags: [linux-openssh] }
    - {
        role: infrastructure/linux-gnome-extensions,
        tags: [linux-gnome-extensions],
      }
    - {
        role: infrastructure/linux-initial-configuration,
        tags: [linux-initial-configuration],
      }
    - { role: infrastructure/postgresql, tags: [postgresql] }
    - { role: infrastructure/zsh, tags: [zsh] }

    # pop-os specific
    - {
        role: infrastructure/popos-initial-configuration,
        tags: [popos-initial-configuration],
        when: ansible_os_family == "Pop!_OS",
      }
    - {
        role: infrastructure/linux-lightdm,
        tags: [linux-lightdm],
        when: ansible_os_family == "Pop!_OS",
      }

    # package manager -> slowly decomposing into separate roles
    - { role: package_manager, tags: [package_manager, bootstrap] }

    # programming languages/frameworks managed by asdf
    - { role: infrastructure/asdf, tags: [asdf] }
    - { role: infrastructure/gohugo, tags: [gohugo] }
    - { role: infrastructure/golang, tags: [golang] }
    - { role: infrastructure/nodejs, tags: [nodejs] }
    - { role: infrastructure/python, tags: [python] }
    - { role: infrastructure/rust, tags: [rust] }

    # - { role: apt, tags: [apt] }

    # cli
    - { role: cli/bat, tags: [bat] }
    - { role: cli/broot, tags: [broot] }
    - { role: cli/cowsay, tags: [cowsay] }
    - { role: cli/csvkit, tags: [csvkit] }
    - { role: cli/diffstat, tags: [diffstat] }
    - { role: cli/fd-find, tags: [fd-find] }
    - { role: cli/gawk, tags: [gawk] }
    - { role: cli/htop, tags: [htop] }
    - { role: cli/jq, tags: [jq] }
    - { role: cli/jump, tags: [jump] }
    - { role: cli/mlocate, tags: [mlocate] }
    - { role: cli/neofetch, tags: [neofetch] }
    - { role: cli/pandoc, tags: [pandoc] }
    - { role: cli/rename, tags: [rename] }
    - { role: cli/ripgrep, tags: [ripgrep] }
    - { role: cli/shellcheck, tags: [shellcheck] }
    - { role: cli/taskwarrior, tags: [taskwarrior] }
    - { role: cli/timewarrior, tags: [timewarrior] }
    - { role: cli/tldr, tags: [tldr] }
    - { role: cli/vim, tags: [vim] }
    - { role: cli/youtube-dl, tags: [youtube-dl] }

    # software
    - { role: software/authy, tags: [authy] }
    - { role: software/brave-browser, tags: [brave-browser] }
    - { role: software/dropbox, tags: [dropbox] }
    - { role: software/google-chrome, tags: [google-chrome] }
    - { role: software/jetbrains-toolbox, tags: [jetbrains-toolbox] }
    - { role: software/joplin, tags: [joplin] }
    - { role: software/kite, tags: [kite] }
    - { role: software/lastpass, tags: [lastpass] }
    - { role: software/linux-blueman, tags: [linux-blueman] }
    - { role: software/linux-conky-manager, tags: [linux-conky-manager] }
    - { role: software/linux-fbreader, tags: [linux-fbreader] }
    - { role: software/linux-flameshot, tags: [linux-flameshot] }
    - { role: software/linux-kazam, tags: [linux-kazam] }
    - { role: software/linux-solaar, tags: [linux-solaar] }
    - { role: software/linux-timeshift, tags: [linux-timeshift] }
    - { role: software/linux-thunderbird, tags: [linux-thunderbird] }
    - { role: software/meld, tags: [meld] }
    - { role: software/obs-studio, tags: [obs-studio] }
    - { role: software/simplenote, tags: [simplenote] }
    - { role: software/slack, tags: [slack] }
    - { role: software/spotify, tags: [spotify] }
    - { role: software/sqlite-browser, tags: [sqlite-browser] }
    - { role: software/sublime-merge, tags: [sublime-merge] }
    - { role: software/sublime-text, tags: [sublime-text] }
    - { role: software/teamviewer, tags: [teamviewer] }
    - { role: software/virtualbox, tags: [virtualbox] }
    - { role: software/vlc, tags: [vlc] }
    - { role: software/vscode, tags: [vscode] }
    - { role: software/whatsapp, tags: [whatsapp] }
    - { role: software/zoom, tags: [zoom] }

    # mac os x
    - { role: macos, tags: [macos], when: ansible_os_family == "Darwin" }
