- name: Set up local workstation
  hosts: local
  roles:
    # - { role: git, tags: ["git"] }
    - { role: package_manager, tags: ["package_manager", "bootstrap"] }
    # - { role: apt, tags: ["apt"] }
    - { role: asdf, tags: ["asdf"] }
    - { role: macos, tags: ["macos"], when: ansible_os_family == "Darwin" }
