---
# main task for whatsapp

- name: whatsapp is present
  become: "{{ should_be_root }}"

  block:
    - name: Install whatsdesk via snap with option --channel=beta
      when: ansible_os_family in ["Debian", "Pop!_OS"]
      snap:
        name: whatsdesk

    - name: Install whatsapp via homebrew cask
      when: ansible_os_family == "Darwin"
      homebrew_cask:
        name: whatsapp
        state: present
