---
# main task for whatsapp

- name: Install whatsapp via homebrew cask
  when: ansible_os_family == "Darwin"
  homebrew_cask:
    name: whatsapp
    state: present


- name: Install whatsdesk via snap with option --channel=beta
  when: ansible_os_family in ["Debian"]
  become: "{{ should_be_root }}"
  snap:
    name: whatsdesk

