---
# main task for slack

- name: slack is present
  become: "{{ should_be_root }}"

  block:
    - name: slack is present (linux)
      when: ansible_os_family in ["Debian", "Pop!_OS"]
      apt:
        deb: "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-{{ machine_map[ansible_machine] }}.deb"

    - name: slack is present (brew cask)
      when: ansible_os_family == "Darwin"
      homebrew_cask:
        name: slack
        state: present
