---
# debian tasks for plex

- name: plex is present in debian
  become: "{{ should_be_root }}"

  block:
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Add Plex apt key (Ubuntu & Debian with systemd)
      apt_key:
        url: https://downloads.plex.tv/plex-keys/PlexSign.key
        state: present

    - name: Add Plex apt repo (Ubuntu & Debian with systemd)
      apt_repository:
        repo: deb https://downloads.plex.tv/repo/deb public main
        state: present
      changed_when: false

    - name: Apt install Plex
      apt:
        name: plexmediaserver
        state: present
        update_cache: true
      notify: restart plex

    - name: Autostart Plex
      service:
        name: plexmediaserver
        enabled: true
      notify: restart plex
