---
# main task for todoist

- name: TODOIST - Install for Darwin
  when: ansible_os_family in ["Darwin"]
  homebrew_cask:
    name: todoist
    state: present


- name: TODOIST - Install for Linux
  when: ansible_os_family in ["Debian"]
  become: "{{ should_be_root }}"
  package:
    name: todoist
    state: present
