---
# main tasks for macos-iterm2

- name: ITERM2 - iterm2 is present (macos)
  block:
    - name: iterm2 is present via brew cask
      homebrew_cask:
        name: iterm2
        state: present

  when: ansible_os_family in ["Darwin"]
