---
# main task for brave-browser

- name: BRAVE-BROWESER - is present
  become: "{{ should_be_root }}"

  block:
    - name: BRAVE-BROWESER - Install brave-browser for MacOS via homebrew cask
      homebrew_cask:
        name: brave-browser
        state: present
      when: ansible_os_family in ["Darwin"]

    - name: BRAVE-BROWESER - brave browser is present for debian system
      block:
        - name: BRAVE-BROWESER - Install repository
          ansible.builtin.deb822_repository:
            name: brave-browser-release
            types: deb
            uris: https://brave-browser-apt-release.s3.brave.com/
            suites: stable
            components: main
            architectures: amd64
            signed_by: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
            state: present

        - name: BRAVE-BROWESER - Install for Debian 
          apt:
            name: brave-browser
            state: present
            update_cache: yes
      when: ansible_os_family in ["Debian"]

