---
# main task for vim


- name: VIM - present for MacOS via homebrew
  when: ansible_pkg_mgr == 'homebrew'
  homebrew:
    name: vim
    state: present


- name: VIM - present for Debian
  become: "{{ should_be_root }}"
  when: ansible_pkg_mgr == 'apt'
  apt:
    name: vim-nox
    state: latest


# Configure
- name: VIM - Check if .vimrc exists
  stat:
    path: "{{ dotfiles_user_home }}/.vimrc"
  register: vimrc_stat
  failed_when: False

- name: VIM - Backup .vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "{{ dotfiles_user_home }}/.vimrc.bak"
  when: vimrc_stat.stat.exists

- name: VIM - Symlink vimrc
  file:
    src: "{{ dotfiles_home }}/files/vimrc"
    dest: "{{ dotfiles_user_home }}/.vimrc"
    state: link
