---
# main task for vim

- name: vim is present
  become: "{{ should_be_root }}"

  block:
    - name: vim is present (apt)
      when: ansible_pkg_mgr == 'apt'
      apt:
        name: vim-nox
        state: latest

    - name: vim is present (homebrew)
      when: ansible_pkg_mgr == 'homebrew'
      homebrew:
        name: vim
        state: present


# Configure
- name: Check if .vimrc exists
  stat:
    path: "{{ dotfiles_user_home }}/.vimrc"
  register: vimrc_stat
  failed_when: False

- name: Backup .vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "{{ dotfiles_user_home }}/.vimrc.bak"
  when: vimrc_stat.stat.exists

- name: Symlink vimrc
  file:
    src: "{{ ansible_dir }}/roles/cli/vim/files/vimrc"
    dest: "{{ dotfiles_user_home }}/.vimrc"
    state: link
