---
# main task for ripgrep

- name: ripgrep is present
  become: "{{ should_be_root }}"

  block:
    - name: ripgrep is present in debian
      apt:
        name: ripgrep
        state: present
        update_cache: yes
        dpkg_options: 'force-overwrite'
      when: ansible_distribution_version is version('18.10', '>') #> 18.10

    - name: ripgrep is present in homebrew
      homebrew:
        name: ripgrep
        state: latest
      when: ansible_os_family in ["Darwin"]
