---
# https://trello.com/

- name: TRELLO|MacOS
  when: ansible_os_family in ["Darwin"]
  community.general.mas:
    id: 1278508951  # Trello
    state: present


- name: TRELLO|Debian|Not implemented
  debug:
    msg: "TODO: Implement for debian?"
