---
- name: Set zsh as default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

  # become: true
- name: Check for .zshrc
  stat:
    path: "{{ dotfiles_user_home }}/.zshrc"
  register: zshrc_stat

- name: Back up .zshrc
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{ dotfiles_user_home }}.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Symlink .p10k.zsh
  file:
    src: "{{ ansible_dir }}/roles/infrastructure/zsh/files/p10k.zsh"
    dest: "{{ dotfiles_user_home }}/.p10k.zsh"
    state: link

- name: Symlink .zshrc
  file:
    src: "{{ ansible_dir }}/roles/infrastructure/zsh/files/zshrc"
    dest: "{{ dotfiles_user_home }}/.zshrc"
    state: link

- name: Get powerlevel10k theme
  command: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k"
  args:
    creates: "{{ dotfiles_user_home }}/.oh-my-zsh/custom/themes/powerlevel10k"

- name: set permissions of powerlevel10k theme
  file:
    path: "{{ dotfiles_user_home }}/.oh-my-zsh/custom/themes/powerlevel10k"
    mode: "go-w"
    recurse: yes

- name: Get plugin zsh-autosuggestions
  command: "git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  args:
    creates: "{{ dotfiles_user_home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Get plugin zsh-syntax-highlighting
  command: "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  args:
    creates: "{{ dotfiles_user_home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Get plugin timewarrior
  command: "git clone https://github.com/svenXY/timewarrior ~/.oh-my-zsh/custom/plugins/timewarrior"
  args:
    creates: "{{ dotfiles_user_home }}/.oh-my-zsh/custom/plugins/timewarrior"

- name: Create directory for plugin poetry
  command: "mkdir ~/.oh-my-zsh/custom/plugins/poetry"
  args:
    creates: "{{ dotfiles_user_home}}/.oh-my-zsh/custom/plugins/poetry"
    warn: false

- name: Enable poetry completions for zsh
  shell: "poetry completions zsh > ~/.oh-my-zsh/custom/plugins/poetry/_poetry"

- name: Create ~/.fonts directory for Linux
  file:
    path: ~/.fonts
    state: directory
  when: ansible_os_family == "Debian" or ansible_os_family == "Pop!_OS"

- name: Install Meslo Nerd Font for Linux
  get_url:
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/{{ item }}"
    dest: "~/.fonts/{{ item }}"
  with_items:
    # regular
    - "MesloLGS%20NF%20Regular.ttf"
    # bold
    - "MesloLGS%20NF%20Bold.ttf"
    # italic
    - "MesloLGS%20NF%20Italic.ttf"
    # italic_bold
    - "MesloLGS%20NF%20Bold%20Italic.ttf"
  when: ansible_os_family in ["Debian", "Pop!_OS"]
