---
- name: Install dependencies for zsh
  become: yes
  package:
    name:
      - git
      - curl
    state: present

- name: Install zsh
  apt:
    name: zsh
    state: present
  become: yes
  become_user: root
  become_method: sudo
