---
# main task for broot

- name: BROOT - broot is present

  block:
    - name: BROOT - install for debian
      include_tasks: debian.yml
      when: ansible_os_family in ["Debian",  "Pop!_OS" ]

    - name: BROOT - install for darwin
      include_tasks: mac.yml
      when: ansible_os_family in ["Darwin"]
