---
# debian task for gh

- name: GH - install for debian machine
  become: "{{ should_be_root }}"
  block:
    - debug:
        msg: "TODO: Hasn't been implemented yet!"
  #   - name: Create temporary download directory
  #     tempfile:
  #       state: directory
  #       suffix: ".gh_binary_download_dir"
  #     register: gh_binary_download_dir

  #   - name: Download gh binary to {{ gh_binary_download_dir.path }}
  #     get_url:
  #       url: https://dystroy.org/gh/download/x86_64-linux/gh
  #       dest: "{{ gh_binary_download_dir.path }}/"
  #       mode: a+x
  #     register: r_gh_binary_download

  #   - debug:
  #       msg: "{{ gh_binary_download_dir.path }}"

  #   - debug:
  #       msg: "{{ r_gh_binary_download }}"

  #   - debug:
  #       msg: "Run command: bash {{ gh_binary_download_dir.path }}/install_gh.sh"

  #   - name: add gh to /usr/local/bin
  #     command: install gh /usr/local/bin
  #     args:
  #       chdir: "{{ gh_binary_download_dir.path }}"

  #   - name: install br shell function
  #     command: /usr/local/bin/gh --install

  # always:
  #   - name: Delete binary download directory - {{ gh_binary_download_dir.path }}
  #     file:
  #       path: "{{ gh_binary_download_dir.path }}"
  #       state: absent
  #     changed_when: no
