---
# install task for nodejs

- name: nodejs & nodejs packages are present

  block:
    - name: Add nodejs plugin for asdf
      command: "asdf plugin-add nodejs {{ nodejs_plugin_url }}"
      register: nodejs_add
      failed_when: nodejs_add == 2

    # 2021-03-09: plugin automatically imports OpenPGP keys
    # - name: Import OpenPGP Key
    #   command: "bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring"

    - name: Symlink .default-npm-packages
      file:
        src: "{{ ansible_dir }}/roles/infrastructure/nodejs/files/default-npm-packages"
        dest: "{{ dotfiles_user_home }}/.default-npm-packages"
        state: link

    - name: Install nodejs versions
      command: asdf install nodejs {{ item }}
      loop: "{{ nodejs_versions }}"
      loop_control:
        label: "{{ item }}"

    - name: Set global version for nodejs to {{ nodejs_versions[0] }}
      command: asdf global nodejs {{ nodejs_versions[0] }}
