---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: true
      notify:
        - Start Nginx

  handlers:
    - name: Start Nginx
      service:
        name: nginx
        state: started
