---
# defaults for linux-openssh

# Currently supported settings are those grouped in the hash below. To override
# a setting, create a key in your inventory and prefix it by `sshd_`. Casing
# must be preserved and is the same as per the 'sshd_config' manual. For
# example, to disable 'PasswordAuthentication', your would add the following key
# in Ansible inventory variables: sshd_PasswordAuthentication: 'no'
sshd_defaults:
  Port: 22
  PermitRootLogin: "prohibit-password"
  ChallengeResponseAuthentication: "no"
  X11Forwarding: "yes"
  ClientAliveInterval: 0
  ClientAliveCountMax: 3
  PasswordAuthentication: "yes"
  StreamLocalBindUnlink: "yes"
  GatewayPorts: clientspecified
  Banner: "none"
