---
# main task for work-macos-software

- name: WORK-MACOS-SOFTWARE - formula and casks are present
  block:
    - name: WORK-MACOS-SOFTWARE - Tap into homebrew & custom taps
      homebrew_tap:
        tap: "{{ item }}"
        state: present
      loop: []

    - name: WORK-MACOS-SOFTWARE - formula are present via homebrew
      homebrew:
        name: "{{ item }}"
        state: present
      loop: 
        - checkov
        - tfsec
        # - kreuzwerker/taps/m1-terraform-provider-helper # 2024-03: Not available

    - name: WORK-MACOS-SOFTWARE - casks are present via homebrew casks
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: 
        # - aviatrix-vpn-client # no longer used as of 2023/03
        - aws-vault
        # - microsoft-outlook
        - microsoft-word
        - microsoft-excel
        - microsoft-powerpoint
        - nosql-workbench
        - onedrive
        - microsoft-remote-desktop

    - name: WORK-MACOS-SOFTWARE|Install via mas
      community.general.mas:
        id: "{{ item.id }}"
        state: present
      loop:
        - "{{ mas_apps['okta_verify'] }}"


  when: ansible_os_family in ["Darwin"]
