---
# main task for work-macos-software

- name: WORK-MACOS-SOFTWARE - formula and casks are present
  block:
    - name: WORK-MACOS-SOFTWARE - Tap into homebrew & custom taps
      homebrew_tap:
        tap: "{{ item }}"
        state: present
      loop: []

    - name: WORK-MACOS-SOFTWARE - formula are present via homebrew
      homebrew:
        name: "{{ item }}"
        state: present
      loop: 
        - checkov
        - tfsec
        - kreuzwerker/taps/m1-terraform-provider-helper

    - name: WORK-MACOS-SOFTWARE - casks are present via homebrew casks
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: 
        - aviatrix-vpn-client
        - aws-vault
        # - microsoft-outlook
        - onedrive
        - microsoft-word
        - microsoft-excel
        - microsoft-powerpoint

  when: ansible_os_family in ["Darwin"]
