---
# main tasks for font-firacode

- name: font-firacode is present
  become: "{{ should_be_root }}"

  block:
    - import_tasks: debian.yml
      when: ansible_os_family in ["Debian",  "Pop!_OS" ]

    - import_tasks: mac.yml
      when: ansible_os_family in ["Darwin"]
