---
# main task for ssh-key

# vars_prompt:
#   - name: "ssh_passphrase"
#     prompt: "Enter the passphrase for the SSH key"
- name: Generate an OpenSSH keypair
  openssh_keypair:
    path: "~/.ssh/{{ ssh_key_filename }}"
    type: rsa
    size: "{{ ssh_key_size }}"
    state: present
    force: no
