---
# main task for ssh-key

# vars_prompt:
#   - name: "ssh_passphrase"
#     prompt: "Enter the passphrase for the SSH key"

- name: Verify ssh_key_filename is provided (e.g. id_rsa_personal_github)
  assert:
    that: 
      - "{{ item }} is defined"
      - "{{ item }} | length > 0"
      - "{{ item }} != None"
    fail_msg: "{{ item }} needs to be set for the role to work"
    success_msg: "Required variable {{ item }} is defined"
  loop_control:
    loop_var: item
  with_items:
    - ssh_key_filename
    - email

# - name: Ensure .ssh directory exists
#   file:
#     path: "{{dotfiles_user_home}}/.ssh"
#     state: directory

# - name: Generate an OpenSSH keypair
#   openssh_keypair:
#     path: "~/.ssh/{{ ssh_key_filename }}"
#     type: ed25519
#     size: "{{ ssh_key_size }}"
#     state: present
#     force: no

- name: Generate SSH keypair for Github
  command: "ssh-keygen -t ed25519 -C {{ email }} -f {{ ssh_key_filename }}"

- name: Post creation message
  debug:
    msg:
    - "For"
    - "Hello"
