---
# Amazon Kindle App

- name: KINDLE|MacOS|Install via mas-cli
  when: ansible_os_family in ["Darwin"]
  community.general.mas:
    id: "{{ mas_apps['kindle'].id }}"
    state: present


- name: KINDLE|Debian|Not implemented
  debug:
    msg: "TODO: Implement for debian?"
