# asdf - languages/frameworks
# NOTE: first plugin version is set to default

golang_plugin_url: https://github.com/kennyp/asdf-golang.git
golang_versions:
  - 1.14.7

nodejs_plugin_url: https://github.com/asdf-vm/asdf-nodejs.git
nodejs_versions:
  - 12.18.3

python_plugin_url: https://github.com/danhper/asdf-python.git
python_versions:
  - 3.8.4
  - miniconda3-4.7.12
pipx_packages:
  - black
  - flake8
  - bpython
  - pipenv

rust_plugin_url: https://github.com/code-lever/asdf-rust.git
rust_versions:
  - stable

gohugo_plugin_url: https://bitbucket.org/mgladdish/asdf-gohugo.git

gohugo_versions:
  - extended_0.75.0
