# Get up and running with large language models, locally. 
# https://ollama.com/


# - name: OLLAMA - Check for installation
#   shell: command -v ollama
#   register: ollama_exists
#   ignore_errors: true


- name: OLLAMA - Install for Linux
  become: "{{ should_be_root }}"
  when: ansible_os_family in ["Debian"] #and ollama_exists is failed
  ansible.builtin.shell:
    cmd: curl -fsSL https://ollama.com/install.sh | sh
  args:
    creates: /usr/local/bin/ollama


# TODO: Implement for Darwin systems
