---
# debian task for brave-browser

- name: brave browser is present for debian system
  block:
    - name: Install Brave Browser key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
        keyring: /etc/apt/trusted.gpg.d/brave-browser-release.gpg
        state: present

    - name: Install Brave Browser repository
      apt_repository:
        repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
        filename: brave-browser-release
        state: present

    - name: Install Brave Browser
      apt:
        name: brave-browser
        state: present
        update_cache: yes
