---
# main task for sqlite-browser

- name: sqlite-browser is present
  become: "{{ should_be_root }}"

  block:
    - name: sqlite-browser is present (linux)
      when: ansible_pkg_mgr != 'homebrew'
      package:
        name: sqlitebrowser
        state: latest

    - name: sqlite-browser is present (homebrew cask)
      when: ansible_pkg_mgr == 'homebrew'
      homebrew_cask:
        name: db-browser-for-sqlite
        state: present
