---
# main task for zoom

- name: ZOOM - Install for Darwin
  when: ansible_os_family == "Darwin"
  homebrew_cask:
    name: zoom
    state: present


- name: ZOOM - Install for Debian
  when: ansible_os_family in ["Debian"]
  apt:
    deb: "https://zoom.us/client/latest/zoom_{{ machine_map[ansible_machine] }}.deb"
