---
# Antigen version number
antigen_version: '2.0.2'

# SHA256 sum for the redistributable package
antigen_redis_sha256sum: 'f47ec933b32c578abe8cb39b24e0ddd114ef5cc01b3c05bcb634859ead31493f'

# Should Oh-My-Zsh be installed with Antigen (doesn't call `antigen use`)
antigen_install_oh_my_zsh: yes

# Mirror location for Antigen download
antigen_redis_mirror: 'https://github.com/zsh-users/antigen/releases/download/v{{ antigen_version }}'

# Directory to store files downloaded from Antigen installation on the remote box
antigen_download_dir: "{{ ansible_env.HOME }}/.ansible/tmp/downloads"
