---
# main task for Rambox
# https://rambox.app/

- name: RAMBOX - Install for MacOS via homebrew cask
  when: ansible_os_family in ["Darwin"]
  homebrew_cask:
    name: rambox
    state: present

- name: RAMBOX - rambox is present for Debian
  become: "{{ should_be_root }}"
  block:
    - name: RAMBOX - Set rambox version (Debian)
      set_fact:
        rambox_version: "0.7.7"

    - name: RAMBOX - Install (Debian)
      apt:
        deb: https://github.com/ramboxapp/community-edition/releases/download/{{ rambox_version }}/Rambox-{{ rambox_version }}-{{ ansible_system | lower }}-{{ machine_map[ansible_machine] }}.deb
  when: ansible_os_family in ["Debian",  "Pop!_OS" ]
