---
# main task for Rambox
# https://rambox.app/

- name: RAMBOX - Install for MacOS via homebrew cask
  when: ansible_os_family in ["Darwin"]
  homebrew_cask:
    name: rambox
    state: present

- name: RAMBOX - present for Debian
  when: ansible_os_family in ["Debian"]
  become: "{{ should_be_root }}"
  block:
    - name: RAMBOX - Getting latest version from Github API
      shell: >
        curl -s https://api.github.com/repos/ramboxapp/community-edition/releases/latest 
        | jq -r '.tag_name'
      register: output

    - name: RAMBOX - Install {{ output.stdout }} (Debian)
      apt:
        deb: https://github.com/ramboxapp/community-edition/releases/download/{{ output.stdout }}/Rambox-{{ output.stdout }}-{{ ansible_system | lower }}-{{ machine_map[ansible_machine] }}.deb
