---
# main task for vlc

- name: VLC - Install for Darwin
  when: ansible_os_family in ["Darwin"]
  homebrew_cask:
    name: vlc
    state: present

- name: VLC - Install for Linux
  when: ansible_os_family in ["Debian"]
  become: "{{ should_be_root }}"
  block:

    - name: VLC - Install via apt (linux)
      apt:
        name: vlc

    - name: VLC - Install extra plugins for vlc (linux)
      apt:
        name: ["vlc-plugin-access-extra", "libbluray-bdj", "libdvdcss2"]
