---
# Handle customizing popos - gnome-tweaks + clean ups
- name: Enabling minimize, maximize, close buttons on the right of titlebar
  command: 'gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"'

- name: Install RestrictedFormats
  apt:
    name: ubuntu-restricted-extras
  become: yes
  become_user: root
  become_method: sudo
