---
# debian task for docker

- name: DOCKER - docker is present for debian system
  block:
    - name: DOCKER - Ensure old versions of Docker are not installed
      package:
        name:
          - docker
          - docker-engine
        state: absent

    - name: DOCKER - Ensure dependencies are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          # - gnupg
          - curl
        state: present
    
    - name: set info
      set_fact:
        docker_repo_url: "https://download.docker.com/linux"

    - name: set info
      set_fact:
        docker_apt_gpg_key: "{{ docker_repo_url }}/ubuntu/gpg"

    - name: DOCKER - Add Docker repository
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: "{{ docker_repo_url }}/ubuntu"
        suites: "{{ ansible_distribution_release }}"
        components: stable
        architectures: amd64
        signed_by: "{{ docker_apt_gpg_key }}"
        state: present

    - name: DOCKER - Update apt cache after adding repository
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
  
    - name: DOCKER - Install Docker
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      notify: restart docker

    - name: DOCKER - Ensure Docker is started and enabled at boot
      service:
        name: docker
        state: started
        enabled: true

    - name: DOCKER - Ensure handlers are notified now to avoid firewall conflicts
      meta: flush_handlers

    - include_tasks: install-docker-compose.yml

    - name: DOCKER - Ensure docker users are added to the docker group
      user:
        name: "{{ item }}"
        groups: [docker]
        append: true
      with_items:
        - johannes
