---
# debian tasks for simplenote

- name: simplenote is present in debian
  become: "{{ should_be_root }}"

  block:
    - name: SIMPLENOTE - Get latest release
      uri:
        url: "https://api.github.com/repos/{{ github_project }}/releases/latest"
        return_content: yes
      register: github_api

    - name: SIMPLENOTE - Register latest release
      set_fact:
        github_release: "{{ github_api.json.tag_name }}"

    - name: SIMPLENOTE - Create temporary directory
      tempfile:
        state: directory
        suffix: ".simplenote_download"
      register: r_simplenote_download_dir

    - name: SIMPLENOTE - Download package
      get_url:
        url: "https://github.com/{{ github_project }}/releases/download/{{ github_release }}/Simplenote-linux-{{ github_release | regex_replace('^v') }}-amd64.deb"
        dest: "{{ r_simplenote_download_dir.path }}/simplenote.deb"
        force: yes

    - name: SIMPLENOTE - Install package
      apt:
        deb: "{{ r_simplenote_download_dir.path }}/simplenote.deb"

    - name: SIMPLENOTE - Remove temporary directory
      file:
        path: "{{ r_simplenote_download_dir.path }}"
        state: absent
    # - name: simplenote is present (linux)
    #   when: ansible_os_family in ["Debian", "Pop!_OS"]
    #   apt:
    #     deb: https://github.com/Automattic/simplenote-electron/releases/download/v1.21.1/Simplenote-linux-1.21.1-amd64.deb
