---
# main task for spotify

- name: SPOTIFY - Install for Darwin
  when: ansible_os_family == "Darwin"
  homebrew_cask:
    name: spotify
    state: present

- name: SPOTIFY - Install for Linux
  when: ansible_os_family in ["Debian"]
  become: "{{ should_be_root }}"
  block:

    - name: Install Spotify key (apt)
      apt_key:
        url: https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg
        state: present

    - name: Install Spotify repository (apt)
      when: ansible_os_family in ["Debian"]
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present

    - name: Install Spotify (apt)
      when: ansible_os_family in ["Debian"]
      apt:
        name: spotify-client
        state: present
        update_cache: true
