---
# main task for spotify

- name: spotify is present
  become: "{{ should_be_root }}"

  block:
    - name: Install spotify (homebrew cask)
      when: ansible_os_family == "Darwin"
      homebrew_cask:
        name: spotify
        state: present

    - name: Install Spotify key (apt)
      when: ansible_os_family in ["Debian", "Pop!_OS"]
      apt_key:
        url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
        state: present

    - name: Install Spotify repository (apt)
      when: ansible_os_family in ["Debian", "Pop!_OS"]
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present

    - name: Install Spotify (apt)
      when: ansible_os_family in ["Debian", "Pop!_OS"]
      apt:
        name: spotify-client
        state: present
