---
- name: Install vscode and dependencies for debian system
  block:
    - name: install dependencies (apt)
      apt:
        name:
          - software-properties-common
          - apt-transport-https
          - wget
        state: present

    - name: Install VS Code repo (apt)
      ansible.builtin.deb822_repository:
        name: vscode
        types: deb
        uris: "{{ visual_studio_code_mirror }}/repos/vscode"
        suites: stable
        components: main
        architectures: amd64
        signed_by: "{{ visual_studio_code_mirror }}/keys/microsoft.asc"
        state: present

    - name: install VS Code (apt)
      apt:
        name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"
        state: present
        update_cache: true
