---
# main tasks for macos-infra(structure)
# TODO: Deal with iterm2 backup file!

- name: MACOS-INFRA - formula, casks and apps are present (macos)

  block:
    - name: MACOS-INFRA - Tap into homebrew & custom taps
      homebrew_tap:
        tap: "{{ item }}"
        state: present
      loop:
        - homebrew/cask-drivers # logitech-options
        - jakehilborn/jakehilborn # displayplacer

    - name: MACOS-INFRA - formulae are present via homebrew
      homebrew:
        name: "{{ item }}"
        state: present
      loop: 
        - mas # Mac App Store command-line interface
        - jakehilborn/jakehilborn/displayplacer

    - name: MACOS-INFRA - casks are present via homebrew cask
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop:
        - aerial
        - alt-tab
        - appcleaner
        - iterm2
        - logi-options-plus
        - logitech-unifying
        - omnidisksweeper
        - rectangle
    
    - name: MACOS-INFRA - apps are present via Mac App Store
      community.general.mas:
        id: "{{ item.id }}"
        state: present
      loop:
        - "{{ mas_apps['clocker'] }}"
        - "{{ mas_apps['displaymenu'] }}"

  when: ansible_os_family in ["Darwin"]
