---
# main task for meld

- name: meld is present
  become: "{{ should_be_root }}"

  block:
    - name: meld is present (linux)
      when: ansible_pkg_mgr != 'brew'
      package:
        name: meld
        state: latest

    - name: access meld via brew tap
      when: ansible_pkg_mgr == 'brew'
      homebrew_tap:
        name: homebrew/cask
        state: present

    - name: meld is present (brew cask)
      when: ansible_pkg_mgr == 'brew'
      homebrew_cask:
        name: meld
        state: present
