---
# main task for meld

- name: meld is present
  become: "{{ should_be_root }}"

  block:
    - name: meld is present (linux)
      when: ansible_pkg_mgr != 'homebrew'
      package:
        name: meld
        state: latest

    - name: meld is present (homebrew cask)
      when: ansible_pkg_mgr == 'homebrew'
      homebrew_cask:
        name: meld
        state: present
