package_upgrade: yes
packages:
  - bison
  - build-essential
  - less
  - libbz2-dev
  - libffi-dev
  - liblzma-dev
  - libncurses5-dev
  - libncursesw5-dev
  - libreadline-dev
  - libssl-dev
  - libsqlite3-dev
  - llvm
  - make
  - man
  - python-openssl
  - software-properties-common
  - tk-dev
  - xclip
  - xz-utils
  - zlib1g-dev
