---
# main task for slack

- name: SLACK - slack is present (brew cask)
  when: ansible_os_family == "Darwin"
  homebrew_cask:
    name: slack
    state: present

- name: SLACK - present for Debian
  become: "{{ should_be_root }}"
  block:
    - name: SLACK - Set slack version
      set_fact:
        slack_version: 4.8.0
        
    - name: SLACK - slack is present (linux)
      when: ansible_os_family in ["Debian", "Pop!_OS"]
      apt:
        deb: "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-{{ machine_map[ansible_machine] }}.deb"

