---
# A new way to see and navigate directory trees
# https://github.com/Canop/broot
# https://dystroy.org/broot/

- name: COMMON-CLI|BROOT - install for darwin
  when: ansible_os_family in ["Darwin"]
  homebrew:
    name: broot
    state: present


- name: COMMON-CLI|BROOT - install for debian
  when: ansible_os_family in ["Debian"]
  community.general.cargo:
    name: broot
    # executable: "{{ ansible_env.HOME }}/.asdf/shims/cargo"
    locked: true
  # environment:
  #   PATH: '{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.asdf/shims'

# Try something new

# - name: COMMON-CLI|BROOT - install for debian
#   when: ansible_os_family in ["Debian"]
#   block:
#   - name: COMMON-CLI|BROOT - install for debian
#     ansible.builtin.shell:
#       cmd: which broots #ommand -v broots # Both command, which return non-zero return code
#     register: broot_install_check
  
#   - name: debug
#     debug:
#       var: broot_install_check
  
#   rescue:
#     - name: COMMON-CLI|BROOT - install for debian
#       ansible.builtin.shell:
#         cmd: echo "Install broot"
    
#     - name: COMMON-CLI|BROOT - Getting latest version from Github API
#       shell: >
#         curl -s https://api.github.com/repos/Canop/broot/releases/latest 
#         | jq -r '.tag_name'
#       register: latest_tag
    
#     - name: Get latest release of a public repository
#       community.general.github_release:
#         user: Canop
#         repo: broot 
#         action: latest_release
#       register: latest
    
#     - name: Debug latest
#       debug:
#         var: latest
    
#     - name: Debug
#       debug:
#         var: latest_tag.stdout
    
#     - meta: end_play

# - name: DEBUG
#   debug:
#     msg: "broot install check:{{ broot_install_check.stdout }}"

# - name: COMMON-CLI|BROOT - install for debian
#   when: broot_install_check.stdout is empty
#   debug:
#     msg: "Installing broot"
# - name: COMMON-CLI|BROOT - install for debian
#   when: ansible_os_family in ["Debian"]
#   include_tasks: install_rust_binary.yml
#   vars:
#     rust_binary_name: broot
#     github_url: https://github.com/Canop/broot
#     github_repo: Canop/broot

  # block:
  #   - name: COMMON-CLI|BROOT - Install Broot key (apt)
  #     become: "{{ should_be_root }}"
  #     apt_key:
  #       url: https://github.com/Canop/broot/releases/download/v1.4.1/broot.gpg
  #       state: present
  #   - name: COMMON-CLI|BROOT - Install Broot repository (apt)

# - name: DEBUG
#   shell:
#     cmd: echo $PATH # --version
#   register: cargo_output

# - name: DEBUG OUTPUT
#   debug:
#     msg: "cargo output:{{ cargo_output }}"

# - name: DEBUG
#   shell:
#     cmd: whoami #cargo --version
#   register: cargo_output

# - name: DEBUG OUTPUT
#   debug:
#     msg: "cargo output:{{ cargo_output }}"


# - name: COMMON-CLI|BROOT - install for debian
#   when: ansible_os_family in ["Debian"]
#   community.general.cargo:
#     name: broot
#     executable: "{{ ansible_env.HOME }}/.asdf/shims/cargo"
#     # locked: true
#   environment:
#     PATH: '{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.asdf/shims'


  # 2024-02 - Deprecated in favor of cargo install
  # become: "{{ should_be_root }}"
  # block:
  #   - name: COMMON-CLI|BROOT - Install Broot key (apt)
  #     become: "{{ should_be_root }}"
  #     # apt-key deprecated
  #     # https://itsfoss.com/apt-key-deprecated/
  #     shell: >
  #       echo "deb [signed-by=/usr/share/keyrings/azlux-archive-keyring.gpg] http://packages.azlux.fr/debian/ stable main" 
  #       | sudo tee /etc/apt/sources.list.d/azlux.list
    
  #       sudo wget -O /usr/share/keyrings/azlux-archive-keyring.gpg  https://azlux.fr/repo.gpg
    
  #   - name: COMMON-CLI|BROOT - Install Broot for Debian
  #     become: "{{ should_be_root }}"
  #     apt:
  #       name: broot
  #       update_cache: yes
