---
# A syntax-highlighting pager for git, diff, and grep output
# https://github.com/dandavison/delta
# https://dandavison.github.io/delta/

- name: COMMON-CLI|DELTA - Install delta via homebrew
  when: ansible_os_family in ["Darwin"]
  homebrew:
    name: git-delta
    state: present


- name: COMMON-CLI|DELTA - Install delta for Debian
  when: ansible_os_family in ["Debian",  "Pop!_OS" ]
  block:
    - name: Getting latest version from Github API
      shell: >
        curl -s https://api.github.com/repos/dandavison/delta/releases/latest 
        | jq -r '.tag_name'
      args:
        warn: false
      register: output
    
    - name: COMMON-CLI|DELTA - install {{ output.stdout }} for debian
      apt:
        deb: https://github.com/dandavison/delta/releases/download/{{ output.stdout }}/git-delta_{{ output.stdout }}_{{ machine_map[ansible_machine] }}.deb
      become: "{{ should_be_root }}"