---
# Jump helps you navigate faster by learning your habits
# https://github.com/gsamokovarov/jump

- name: COMMON-CLI|JUMP - Install via homebrew
  when: ansible_pkg_mgr == 'homebrew'
  homebrew:
    name: jump
    state: present


- name: COMMON-CLI|JUMP - Install for Darwin
  when: ansible_os_family in ["Debian", "Pop!_OS"]
  block:
    - name: Getting latest version from Github API
      shell: >
        curl -s https://api.github.com/repos/gsamokovarov/jump/releases/latest 
        | jq -r '.name'
      args:
        warn: false
      register: output

    - name: COMMON-CLI|JUMP - Install {{ output.stdout }} Debian package
      apt:
        deb: https://github.com/gsamokovarov/jump/releases/download/v{{ output.stdout }}/jump_{{ output.stdout }}_{{ machine_map[ansible_machine] }}.deb
      become: "{{ should_be_root }}"