---
# main task for common-cli

- name: COMMON-CLI - common-cli are present

  block:
    - name: COMMON-CLI - Install packages via default package manager
      become: "{{ should_be_root }}"
      package:
        name: "{{ item[ansible_pkg_mgr] | default(item['default']) }}"
        state: latest
      # Filter out cargo packages (better than conditional clause)
      loop: "{{ packages | selectattr('default', 'defined')}}"


    - name: COMMON-CLI|APT - Install packages via apt (Debian)
      when: ansible_os_family in ["Debian"]
      package:
        name: "{{ item[ansible_pkg_mgr] | default(item['default']) }}"
        state: latest
      loop: "{{ packages | selectattr('apt', 'defined')}}"


    # some packages are easier to install via cargo
    - name: COMMON-CLI|CARGO - Install packages via cargo (Darwin)
      when: ansible_os_family in ["Debian"]
      community.general.cargo:
        name: "{{ item['cargo'] }}"
        executable: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
        locked: true
      loop: "{{ packages | selectattr('cargo', 'defined') | selectattr('homebrew', 'undefined') }}"


    - name: COMMON-CLI|HOMEBREW - Install packages via homebrew (Darwin)
      when: ansible_os_family in ["Darwin"]
      package:
        name: "{{ item[ansible_pkg_mgr] | default(item['default']) }}"
        state: latest
      loop: "{{ packages | selectattr('homebrew', 'defined') | selectattr('default', 'undefined') }}"

    - import_tasks: jump.yml
    - import_tasks: noti.yml
    # - import_tasks: macos.yml
    - import_tasks: uv.yml


# EZA
- name: COMMON-CLI|EZA - get completions from github
  ansible.builtin.get_url:
    url: https://github.com/eza-community/eza/tree/main/completions/zsh/_eza
    dest: "{{ dotfiles_user_home }}/.zfunc/_eza"

- name: COMMON-CLI|BROOT - Initialize manually
  debug:
    msg: "Run broot manually to initialize"
