---
# main task for common-cli

- name: COMMON-CLI - common-cli are present
  become: "{{ should_be_root }}"

  block:
    - name: COMMON-CLI - common-cli packages are present
      package:
        name: "{{ item[ansible_pkg_mgr] | default(item['default']) }}"
        state: latest
      loop: "{{ common_packages }}"

    - import_tasks: broot.yml
    - import_tasks: delta.yml
    - import_tasks: jump.yml
    - import_tasks: noti.yml


# EXA
- name: COMMON-CLI|EXA - get completions from github
  ansible.builtin.get_url:
    url: https://github.com/ogham/exa/blob/master/completions/zsh/_exa
    dest: "{{ dotfiles_user_home }}/.zfunc/_exa"
