# https://github.com/astral-sh/uv
# An extremely fast Python package installer and resolver, written in Rust.


- name: COMMON-CLI|UV - Check for installation
  ansible.builtin.command: command -v uv
  register: package_check
  ignore_errors: true

- name: COMMON-CLI|UV - Already installed
  debug:
    msg: "UV is already installed - {{ package_check.stdout }}"
  when: package_check is succeeded

- name: COMMON-CLI|UV - Install
  ansible.builtin.shell: curl -LsSf https://astral.sh/uv/install.sh | sh
  when: package_check is failed
