---
# main task for lastpass

- name: LASTPASS - Install lastpass for MacOS via homebrew cask
  homebrew_cask:
    name: lastpass
    state: present


- name: LASTPASS - present for debian machine
  block:
    - name: LASTPASS - Create temporary download directory
      tempfile:
        state: directory
        suffix: ".lastpass_installation_download_dir"
      register: lastpass_installation_download_dir

    - name: LASTPASS - Download lastpass installer to {{ lastpass_installation_download_dir.path }}
      get_url:
        url: https://download.cloud.lastpass.com/linux/lplinux.tar.bz2
        dest: "{{ lastpass_installation_download_dir.path }}/"
        mode: a+x
      register: r_lastpass_installer_download

    - debug:
        msg: "{{ lastpass_installation_download_dir.path }}"

    - debug:
        msg: "{{ r_lastpass_installer_download }}"

    - name: LASTPASS - Unarchive lastpass installation file {{ r_lastpass_installer_download.dest }}
      unarchive:
        src: "{{ r_lastpass_installer_download.dest }}"
        dest: "{{ lastpass_installation_download_dir.path }}"

    - debug:
        msg: "Run command: bash {{ lastpass_installation_download_dir.path }}/install_lastpass.sh"
  # always:
  #   - name: Delete installation download directory - {{ lastpass_installation_download_dir.path }}
  #     file:
  #       path: "{{ lastpass_installation_download_dir.path }}"
  #       state: absent
  #     changed_when: no
  when: ansible_os_family in ["Debian"]