---
# main tasks for postgres

- name: postgres is present
  become: "{{ should_be_root }}"

  block:
    # variable configuration
    - include_tasks: variables.yml

    # Setup/install tasks
    - import_tasks: debian.yml
      when: ansible_os_family in ["Debian",  "Pop!_OS" ]

    - import_tasks: mac.yml
      when: ansible_os_family in ["Darwin"]

    - include_tasks: initialize.yml
    - include_tasks: configure.yml

    - name: Ensure PostgreSQL is started and enabled on boot.
      service:
        name: "{{ postgresql_daemon }}"
        state: "{{ postgresql_service_state }}"
        enabled: "{{ postgresql_service_enabled }}"

    # Configure PostgreSQL
    - import_tasks: users.yml
    - import_tasks: databases.yml
