---
# main task for noti

- name: NOTI - Install via homebrew for Darwin
  homebrew:
    name: noti
    state: present
  when: ansible_os_family in ["Darwin"]


- name: NOTI - install for debian machine
  when: ansible_os_family in ["Debian",  "Pop!_OS" ]
  block:
    - name: NOTI - Create temporary download directory
      tempfile:
        state: directory
        suffix: ".noti_binary_download_dir"
      register: noti_binary_download_dir

    - name: NOTI - Set noti version
      set_fact:
        noti_version: "3.5.0"
    
    - name: NOTI - Set noti_system_map
      set_fact:
        noti_system_map:
          Darwin: macos
          Linux: linux

    - name: NOTI - Register folder name
      set_fact:
        noti_folder_name: "noti{{ noti_version }}.{{ noti_system_map[ansible_system] }}-{{ machine_map[ansible_machine] }}"

    - name: Download noti binary to {{ noti_binary_download_dir.path }}
      ansible.builtin.unarchive:
        src: "https://github.com/variadico/noti/releases/download/{{ noti_version }}/{{ noti_folder_name }}.tar.gz"
        dest: "{{ noti_binary_download_dir.path }}/"
        remote_src: yes
      register: r_noti_unarchive

    - debug:
        msg: "{{ noti_binary_download_dir.path }}"

    - debug:
        msg: "Run command: sudo install {{ noti_binary_download_dir.path }}/noti /usr/local/bin"

    - name: add noti to /usr/local/bin
      command: install noti /usr/local/bin
      args:
        chdir: "{{ noti_binary_download_dir.path }}"
      become: "{{ should_be_root }}"

  always:
    - name: Delete binary download directory - {{ noti_binary_download_dir.path }}
      file:
        path: "{{ noti_binary_download_dir.path }}"
        state: absent
      changed_when: no
