---
# main task for bat

- name: bat is present
  become: "{{ should_be_root }}"

  block:
    - name: BAT - present in debian
      apt:
        name: bat
        state: present
        update_cache: yes
        dpkg_options: "force-overwrite"
      when: ansible_os_family in ['Debian', 'Pop!_OS']

    - name: BAT - present (homebrew)
      homebrew:
        name: bat
        state: latest
      when: ansible_os_family in ["Darwin"]
