---
# main task for vim

- name: vim is present
  become: "{{ should_be_root }}"

  block:
    - name: vim is present (apt)
      when: ansible_pkg_mgr == 'apt'
      apt:
        name: vim-nox
        state: latest

    - name: vim is present (homebrew)
      when: ansible_pkg_mgr == 'homebrew'
      homebrew:
        name: vim
        state: present

- import_tasks: configure.yml
