---
# debian task for docker

- name: docker is present for debian system
  block:
    - name: Ensure old versions of Docker are not installed
      package:
        name:
          - docker
          - docker-engine
        state: absent

    - name: Ensure dependencies are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg2
        state: present

    - name: Add Docker apt key
      apt_key:
        url: "{{ docker_apt_gpg_key }}"
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present
      register: add_repository_key
      ignore_errors: "{{ docker_apt_ignore_key_error }}"

    - debug:
        msg: "repository: {{ docker_apt_repository }}"

    - name: Add Docker repository
      apt_repository:
        repo: "{{ docker_apt_repository }}"
        state: present
        update_cache: true

    - name: Install Docker
      package:
        name: "{{ docker_package }}"
        state: "{{ docker_package_state }}"
      notify: restart docker

    - name: Ensure Docker is started and enabled at boot
      service:
        name: docker
        state: "{{ docker_service_state }}"
        enabled: "{{ docker_service_enabled }}"

    - name: Ensure handlers are notified now to avoid firewall conflicts
      meta: flush_handlers

    - include_tasks: debian-docker-compose.yml
      when: docker_install_compose | bool

    - include_tasks: debian-docker-users.yml
      when: docker_users | length > 0

    - name: Ensure /var/run/docker.sock has correct permissions
      file:
        path: /var/run/docker.sock
        mode: "666"
