---
# main tasks for macos-infra(structure)

- name: MACOS-INFRA - formula, casks and apps are present (macos)

  block:
    - name: MACOS-INFRA - Tap into homebrew & custom taps
      homebrew_tap:
        tap: "{{ item }}"
        state: present
      loop: "{{ macos_homebrew_taps }}"

    - name: MACOS-INFRA - formulae are present via homebrew
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ macos_infrastructure_formulae }}"

    - name: MACOS-INFRA - casks are present via homebrew cask
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ macos_infrastructure_casks }}"
    
    - name: MACOS-INFRA - apps are present via Mac App Store
      community.general.mas:
        id: "{{ item.id }}"
        state: present
      loop: "{{ macos_mas_apps }}"

  when: ansible_os_family in ["Darwin"]
