---
# main tasks for macos-infra(structure)

- name: MACOS-INFRA - formula and casks are present (macos)

  block:
    - name: MACOS-INFRA - Tap into homebrew & custom taps
      homebrew_tap:
        tap: "{{ item }}"
        state: present
      loop: "{{ macos_homebrew_taps }}"

    - name: MACOS-INFRA - formula are present via homebrew
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ macos_infrastructure_formula }}"

    - name: MACOS-INFRA - casks are present via homebrew cask
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ macos_infrastructure_casks }}"

  when: ansible_os_family in ["Darwin"]
