---
# main task for golang


- name: GOLANG - Set Golang Versions
  set_fact:
    golang_versions:
      - 1.18
      - 1.16.14

- name: GOLANG - golang & golang packages are present

  block:
    - name: GOLANG - Install dep apt package
      when: ansible_os_family in ["Debian"]
      apt:
        name: go-dep
      tags: [golang-install]

    - name: GOLANG - Add golang plugin for asdf (https://github.com/kennyp/asdf-golang.git)
      command: asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
      register: golang_add
      failed_when: golang_add == 2
      tags: [golang-install]

    # - name: Symlink .default-golang-pkgs
    #   file:
    #     src: "{{ dotfiles_home }}/files/.default-golang-pkgs"
    #     dest: "{{ dotfiles_user_home }}/.default-golang-pkgs"
    #     state: link

    - name: GOLANG - Install golang versions
      command: asdf install golang {{ item }}
      loop: "{{ golang_versions }}"
      loop_control:
        label: "{{ item }}"

    - name: GOLANG - Set global version for golang to {{ golang_versions[0] }}
      command: asdf global golang {{ golang_versions[0] }}

    - name: GOLANG - Create ~/go directory
      file:
        path: "{{ dotfiles_user_home }}/go"
        state: directory
