---
# debian tasks for audacity

- name: AUDACITY - is present for debian system

  block:
    - name: AUDACITY - add repository
      apt_repository:
        repo: "ppa:ubuntuhandbook1/audacity"
        state: present

    - name: AUDACITY - Update repositories cache and install audacity (debian)
      apt:
        name: audacity
        update_cache: yes
