---
# main task for google-chrome

- name: google chrome is present
  become: "{{ should_be_root }}"

  block:
    - name: google-chrome-stable is present (linux)
      when: ansible_pkg_mgr != 'brew'
      package:
        name: google-chrome-stable
        state: latest

    - name: google-chrome is present (brew)
      when: ansible_pkg_mgr == 'brew'
      homebrew_cask:
        name: google-chrome
        state: present
