---
# The Remote Connectivity Software
# https://www.teamviewer.com/en-ca/

- name: Install Teamviewer (brew-cask)
  when: ansible_os_family == "Darwin"
  homebrew_cask:
    name: teamviewer
    state: present


- name: TEAMVIEWER|Install for Debian
  when: ansible_os_family in ["Debian"]
  become: "{{ should_be_root }}"
  ansible.builtin.package:
    name: teamviewer 
    state: present
  check_mode: true
  register: package_check
  ignore_errors: true

- name: TEAMVIEWER|Install for Debian
  when: package_check is failed and ansible_os_family in ["Debian"]
  become: "{{ should_be_root }}"
  block:

    - name: TEAMVIEWER|Install dependencies
      ansible.builtin.apt:
        name:
          - libxtst6
          - libqt5dbus5
          - libqt5widgets5
          - libqt5qml5
          - libqt5quick5
          - libqt5gui5
          - libqt5core5a

    - name: TEAMVIEWER|Create temporary download directory
      tempfile:
        state: directory
        suffix: ".teamviewer"
      register: download_dir

    - name: TEAMVIEWER|Get package
      ansible.builtin.get_url:
        url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
        dest: "{{ download_dir.path }}"
      register: deb_file
    
    - debug:
        msg: 
          - "URL: {{ deb_file.url }}"
          - "DEST: {{ deb_file.dest }}"
    
    - name: TEAMVIEWER|Install Teamviewer
      ansible.builtin.apt:
        deb: "{{ deb_file.dest }}"
    
    - debug:
        msg: "NOTE: Restart computer!"

  always:
    - name: TEAMVIEWER|Delete temporary download directory
      file:
        path: "{{ download_dir.path }}"
        state: absent
      changed_when: no
